services:
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - web
    restart: unless-stopped

  nginx:
    container_name: nginx
    image: nginx:1.27-alpine
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
    volumes:
      - ./nginx/assets.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      - web
    restart: unless-stopped

networks:
  web:
    driver: bridge
    